# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: postgresql
  host: localhost
  database: FunnyArticlesDB
  username: username
  password: password
test: &test
  adapter: postgresql
  host: localhost
  database: FunnyArticlesDB_test
  username: username
  password: password